from typing import Dict, List

FIELD_LEXICON: Dict[str, List[str]] = {
    "manufacturer": [
        "manufactured by",
        "mfd by",
        "mfg by",
        "made by",
        "producer",
    ],
    "packer": [
        "packed by",
        "pkd by",
        "packing by",
    ],
    "importer": [
        "imported by",
        "import by",
    ],
    "marketer": [
        "marketed by",
        "mkt by",
        "marketing by",
    ],
    "country_of_origin": [
        "country of origin",
        "made in",
        "origin",
    ],
    "net_quantity": [
        "net quantity",
        "net qty",
        "net wt",
        "net weight",
        "net vol",
        "net volume",
        "net content",
        "net contents",
        "net quantity / net weight",
        "net weight / net quantity",
        "contents",
        "शुद्ध मात्रा",
    ],
    "mrp": [
        "maximum retail price",
        "max retail price",
        "mrp",
        "m r p",
        "m.r.p.",
        "m.r.p",
    ],
    "unit_sale_price": [
        "unit sale price",
        "usp",
        "unit price",
    ],
    "mfg_date": [
        "date of mfg",
        "date of manufacture",
        "manufactured on",
        "mfg date",
        "mfd date",
        "pkd date",
        "packed date",
        "date of pkd",
        "date of packing",
        "pack date",
        "mfd",
        "mfg",
        "mfg.",
        "pkd",
        "packed",
    ],
    "best_before": [
        "best before",
        "use by",
        "expiry date",
        "expiry",
        "exp date",
        "exp.",
        "exp",
    ],
    "consumer_care": [
        "consumer care",
        "customer care",
        "consumer complaints",
        "customer complaints",
        "for feedback",
        "contact us",
        "for queries",
    ],
}
