from typing import Dict, List

FIELD_LEXICON: Dict[str, List[str]] = {
    "manufacturer": [
        "manufactured in india by",
        "manufactured by",
        "mfd by",
        "mfg by",
        "md by",
        "mfd.by",
        "mfg.by",
        "mid.by",
        "manufactured for",
        "mfd for",
        "mfg lic no",
        "made by",
        "producer",
        "regd office",
        "registered office",
        "regd. office",
    ],
    "packer": [
        "packed by",
        "pkd by",
        "packing by",
    ],
    "importer": [
        "imported by",
        "import by",
    ],
    "marketer": [
        "marketed by",
        "mktd by",
        "mkto.by",
        "mkt by",
        "marketing by",
        "arketed by",
    ],
    "country_of_origin": [
        "country of origin",
        "made in",
        "origin",
    ],
    "net_quantity": [
        "net quantity",
        "net qty",
        "net wt",
        "net weight",
        "net vol",
        "net volume",
        "net content",
        "net contents",
        "net quantity / net weight",
        "net weight / net quantity",
        "contents",
        "शुद्ध मात्रा",
    ],
    "mrp": [
        "maximum retail price",
        "max retail price",
        "mrp",
        "m r p",
        "m.r.p.",
        "m.r.p",
    ],
    "unit_sale_price": [
        "unit sale price",
        "usp",
        "unit price",
    ],
    "mfg_date": [
        "date of mfg",
        "date of manufacture",
        "manufactured on",
        "mfg date",
        "mfd date",
        "pkd date",
        "packed date",
        "date of pkd",
        "date of packing",
        "pack date",
        "mfg.&expiry",
        "mfd &",
        "batch no",
        "mfd",
        "mfg",
        "mfg.",
        "pkd",
        "packed",
    ],
    "best_before": [
        "best before",
        "use by",
        "expiry date",
        "expiry",
        "exp date",
        "exp.",
        "exp",
    ],
    "consumer_care": [
        "consumer care",
        "customer care",
        "consumer cell",
        "consumer complaints",
        "customer complaints",
        "cares",
        "call or write",
        "for feedback",
        "for queries",
        "helpline",
        "toll free",
        "e-mail",
    ],
    "generic_name": [
        "generic name",
        "common name",
        "name of commodity",
        "name of the commodity",
        "commodity",
    ],
}
